### ISSUE TITLE
Missing filepath in "Replace Rails' stylesheets by Le Wagon's stylesheets"

### ISSUE THREAD

**Issue by nonrevolver** [barangerbenjamin/wsl-issues#1]
> Move the download custom stylesheets in the our new folder:
` mv rails-stylesheets-master/* app/assets/stylesheets `

is missing directory path:
`mv app/assets/rails-stylesheets-master/* app/assets/stylesheets`

**Comment by barangerbenjamin** [comment]
Thanks for the issue @nonrevolver 🙏 
Fixed by https://github.com/barangerbenjamin/wsl-issues/commit/60c04a824fd80952b711af31c3541863e8162758#diff-04c6e90faac2675aa89e2176d2eec7d8
